Repository UBCO-COSC499-Winter-2018-Term-1-2/visual-course-planner, pull requests merged in 2019-04, with the labels that each got.

#99 Fix autosave
  README.md
  client/package-lock.json
  client/src/components/AdminPortal/AdminPortal.js
  client/src/components/NewPlan/NewPlan.js
  client/src/components/PlanList/PlanList.css
  client/src/components/PlanList/PlanList.js
  client/src/components/PlanName/PlanName.css
  client/src/components/PlanName/PlanName.js
  client/src/components/Planner/PlannerArea.js
  client/src/components/PlannerHeader/PlannerHeader.js
  client/src/components/UserProfile/Profile.js
  client/src/containers/Main.css
  client/src/containers/Main.js
  database.sql
  package-lock.json
  server.js
  server/src/config/passport.js
  server/src/models/Course.js
  server/src/models/Plan.js
  server/src/models/Specialization.js
  server/src/models/User.js
  server/src/routes/api/admin/upload.js
  server/src/routes/api/courses.js
  server/src/routes/api/plans.js
  server/src/routes/api/users.js
Labels: bug

#102 Set max request size.
  client/src/components/ConfirmEmail/ConfirmEmail.js
  server.js
  server/src/routes/api/users.js
Labels: bug, deploy

#77 Time logs Jan 14-27
  docs/weekly logs/herraj/11th Feb - 29th Feb.pdf
  docs/weekly logs/herraj/March 1st - 31st.pdf
  docs/weekly logs/herraj/Month of April.pdf
  docs/weekly logs/herraj/Weekly log - Jan 14-27.pdf
  docs/weekly logs/herraj/Weekly log - Jan 28 - feb 10.pdf
  docs/weekly logs/jaskaran/2019-02-11-2019-03-03.pdf
  docs/weekly logs/jaskaran/Feb 4-10th.pdf
  docs/weekly logs/jaskaran/Jan 21- 27th.pdf
  docs/weekly logs/jaskaran/Jan. 14th - Jan. 20th.pdf
  docs/weekly logs/jaskaran/March 4th- April 11th.pdf
  docs/weekly logs/mackenzie/Week of Apr 1.pdf
  docs/weekly logs/mackenzie/Week of Apr 8.pdf
  docs/weekly logs/mackenzie/Week of Feb 11.pdf
  docs/weekly logs/mackenzie/Week of Feb 18.pdf
  docs/weekly logs/mackenzie/Week of Feb 25.pdf
  docs/weekly logs/mackenzie/Week of Mar 11.pdf
  docs/weekly logs/mackenzie/Week of Mar 18.pdf
  docs/weekly logs/mackenzie/Week of Mar 25.pdf
  docs/weekly logs/mackenzie/Week of Mar 4.pdf
  docs/weekly logs/mackenzie/Weeks of Feb 11.pdf
  docs/weekly logs/mackenzie/Weeks of Jan 14.pdf
  docs/weekly logs/mackenzie/Weeks of Jan 28.pdf
  docs/weekly logs/noman/Timelog_2019-01-14_to_2019-01-27.pdf
  docs/weekly logs/noman/Timelog_2019-01-28_to_2019-02-10.pdf
  docs/weekly logs/noman/Timelog_2019-02-11_2019-03-03.pdf
  docs/weekly logs/noman/Timelogs_2019-03-04_2019-04-13.pdf
  docs/weekly logs/project/Nov 5 to Apr 14.pdf
  docs/weekly logs/taylor/TaylorToggle_2019-01-29_2019-02-10.pdf
  docs/weekly logs/taylor/taylorToggle2019-02-11_2019-03-03.pdf
  docs/weekly logs/taylor/taylorToggle_2019-01-14_2019-01-27.pdf
  docs/weekly logs/taylor/taylorToggle_2019-03-04_2019-03-31.pdf
  docs/weekly logs/taylor/taylorToggle_2019-04-01_2019-04-14.pdf
Labels: documentation
